### ISSUE TITLE
Kurs beitreten

### ISSUE THREAD

**Issue by myPhilie** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#13]

**Comment by myPhilie** [comment]
- Eingegebene Beitrittsnummer überprüfen
- Bei gültiger Nummer Beitritt in Kurs
- Bei ungültiger Nummer "Fehlermeldung" anzeigen

**Comment by vairasza** [comment]
DECISSION:
- database key equals to course id
- for MVP we only have one course --> users should to add another course
- after registering a course, user directly lands in the first thread


TODO:
- replace courseId in database for this key
- add participantslist to each course which means that they are registered
- render text messages
- push new messages to database
- set listeners for database changes and render incoming messages (https://firebase.google.com/docs/database/android/lists-of-data)

**Comment by vairasza** [comment]
fertig implementiert
