### ISSUE TITLE
UI Problems

### ISSUE THREAD

**Issue by julian1198** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#135]
### Allgemein
- [x] Erstellen von Coursen/Meetings/Threads: Stringlängen begrenzen.
- [x] Kursübersicht: Teilnehmer stylen und Problem für schwarze Bilder finden (ggf Bindingapter setImage Problem)
- [x] Buttons können nicht von grau auf blau resetet werden. (z.b. LoginFragment) für mehr Infos Micha fragen => Lösung: [link](https://stackoverflow.com/a/55546253/13620136)
- [x] course_meeting_menu.xml -> filter item hat tooltip "suche"
- [x] searchview aus toolbar entfernen
- [x] bei com.google.android.material.textfield.TextInputLayout "app:endIconMode="clear_text" hinzufügen, um Eingaben auf einmal zu löschen
- [x] <app:counterEnabled="true"> und <app:counterMaxLength="15"> bei login/registration/entercourse/erstellungsfragments hinzufügen, damit der nutzer sieht wie viel text er noch eingeben darf
- [x] zurück-button einheitlich färben (bei sekundären buttons sieht man teils auch nur die schrift)
- [x] looper in createThread/createPoll etc. einfügen
- [x] SearchView TextColor -> white
- [x] bei Screens die nicht auf eine Seite passen, evtl. sichtbare Scrollbar einfügen (Login, CreateMeeting, etc.)

### Login
- [x] Screen auf kleinerem Bildschirm nicht mehr ganz sichtbar
- [x] Logo kleiner machen, damit alles auch auf kleine Screens passt

### Registration
- [x] Abstände bei Title "Registrierung" oben und unten kleiner machen

### Email-Verifikation
- [x] Design anpassen
- [x] Bild zu groß

### Kursübersicht
- [x] Profilbild laden statt Standardavatar

### Profil
- [x] aktuellen Zustand anzeigen
- [ ] Placeholder (z.B. bestimmte Uni bei Institution reinschreiben bzw reinschreiben Istzustand)
- [x] save-buttons anpassen, sodass man einen looper unterbringt
- [x] button soll wie andere buttons in der app aussehen (einheitliches design)

### Kurs beitreten
- [ ] EnterCourseFragment: Tastatur anpassen
- [x] EnterCourseFragment umbauen, sodass man [Link](https://github.com/yuriy-budiyev/code-scanner) verwenden kann
- [x] Kursinfos zu klein (bei Beitritt)
- [x] evtl. genaueren Hinweis über Situation (z.B. "Du bist gerade dabei, diesem Kurs beizutreten")

### Meeting erstellen
- [x] Design Eingabefelder anpassen
- [x] Endzeit ist kleiner als andere Eingabefelder
- [x] Design Button anpassen
- [x] Endzeit defaultmäßig auf Startzeit + x setzen
- [ ] Pfeilicons ans Ende von Datum und Startzeit? ider icon davor

### Kursbeschreibung
- [ ] Placeholder für leere Felder
- [x] Beitrittscode so anzeigen lassen, damit man ihn ablesen/weitersagen kann

### Fragen
- [x] Plus-Fab hat einen leicht grünlichen Rand
- [ ] Icons bei Seitenzahl-Chips werden überdeckt wenn ausgewählt --> leider keine Lösung gefunden
- [ ] evtl. Design von Chip-Container allgemein anpassen

### Frage erstellen
- [x] Wording auf Frage umstellen
- [x] Aktiv-Haken bei Sonstiges nicht sichtbar (beides schwarz)

### Thread
- [x] Toolbar scheint etwas groß
- [x] Karten optimieren (Überschneidungen, andere Aufteilung, etc.)
- [x] Blaue Farbe für Name könnte verwirrend sein und Klick darauf andeuten

### Onboarding
- [ ] Scrollview damit TextView über Keyboard angezeigt wird
- [ ] ggf Tabs in der Mitte anzeigen

**Comment by julian1198** [comment]
AnswerItem: Nur Like/dislike Verhältniss nicht likes und dislike Anzahl

**Comment by vairasza** [comment]
Meeting Fragment:

- [ ] close button für das popup in welchem ein neues meeting angelegt werden kann, fehlt. hab nen platzhalter rein.
- [ ] MeetingModel hab ich eventime und creationtime zu nem String geändert, da sich das sonst mit databinding beißt. muss man dann im viewmodel oder so halt casten.

**Comment by vairasza** [comment]
ThreadModel braucht noch eine property für die Anzahl der Antworten

**Comment by myPhilie** [comment]
> Meeting Fragment:
> 
> * [x]  close button für das popup in welchem ein neues meeting angelegt werden kann, fehlt. hab nen platzhalter rein.

Das Popup wird durch einen neuen Screen ersetzt, wodurch dieser Punkt hinfällig wird

**Comment by vairasza** [comment]
![Screenshot 2022-03-04 at 10 00 28](https://user-images.githubusercontent.com/46536619/156732506-f4fbc404-23e8-4f3b-8180-2c0d8e5f239f.png)

**Comment by vairasza** [comment]
- [ ] bei den RecyclerView Items bitte onclick das Item hervorheben, damit der User sieht, dass das Item geklickt wurde.
