### ISSUE TITLE
Datenstruktur topAnswer + answered

### ISSUE THREAD

**Issue by julian1198** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#156]
In der Datenstruktur sind Fehler bei dem Zusammenspiel zwischen beantworteten threads und topAnswers. Seitdem die neuen hochgeladen sind stimmen diese nicht mehr über ein. Beispiel: Thread mit ID: cf861b7a-1611-4e47-a18f-57476f797a7c ist als beantwortet markiert, aber keine Antwort ist topAnswer.

**Comment by vairasza** [comment]
hab den fehler in dem testdatenskript gefunden und behoben. daten hab ich in der db aktualisiert.
