### ISSUE TITLE
Anzeigen des Nutzernamens von gelöschten Accounts

### ISSUE THREAD

**Issue by julian1198** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#161]
- [x] Die Nutzernamen von gelöschten Accounts werden auch aus der Datenbank entfernt. Wird ein solcher Nutzer nun als Verfasser einer Nachricht angezeigt muss anstelle des Namens ein Vermerk auf einen glöschten Account gemacht werden.

**Comment by julian1198** [comment]
<gelöschter Nutzer> (<> mit inbegriffen) wird im Augenblick als Name für gelöschte Accounts angezeigt. Ist das in Ordnung?

**Comment by myPhilie** [comment]
> <gelöschter Nutzer> (<> mit inbegriffen) wird im Augenblick als Name für gelöschte Accounts angezeigt. Ist das in Ordnung?

Finde ich in Ordnung

**Comment by Rusi91** [comment]
Finde ich nützlich für folgende Fälle.

**Nutzer*in ist Kursmitglied und stellt oder beantwortet eine Frage.** Sobald Nutzer*in nicht mehr existiert, sollten die Fragen und Antworten des/r Nutzer*in für andere Kursmitglieder erhalten bleiben.

**Nutzer*in ist Kursersteller*in.** Sobald Nutzer*in nicht mehr existiert, sollte der Kurs mit seinen Fragen und Antworten für ehemalige Kursmitglieder erhalten bleiben, indem der Kurs in der Form fortbesteht, dass zwar keine neuen Meetings dazukommen, jedoch die vorhandenen Meetings erhalten bleiben.
