### ISSUE TITLE
(MEETINGS) Anpassung der Anzeige wenn (heute) keine Meetings stattfinden.

### ISSUE THREAD

**Issue by Rusi91** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#173]
- [ ] Wenn an dem aktuellen Tag keine Meetings stattfinden wird angezeigt, dass keine Kurse stattfinden. Sollte lieber stehen, dass heute keine Meetings stattfinden.

**Comment by Rusi91** [comment]
![heuteRecyclerView Fehler](https://user-images.githubusercontent.com/41992838/157677483-70994954-f0aa-4c13-bbf7-62e959f65977.png)

**Comment by myPhilie** [comment]
Ich finde das passt eigentlich so. So halten wir auch die Sprache konsistent
