### ISSUE TITLE
(PROFILE) Wenn man sein Passwort ändert, wird auch die FirebaseAuth ID geändert => in erstellten Kursen kann man keine Meetings erstellen

### ISSUE THREAD

**Issue by vairasza** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#174]

**Comment by julian1198** [comment]
Es wird nicht die FirebaseId geändert. Der Fehler ist durch ein Fehler beim Laden entstanden. Das Laden wurde in 618db84d66478f642f008ad490bee1c1f2a36cb3 angepasst. Der Fehler sollte also nicht mehr auftreten.
