### ISSUE TITLE
(LOGIN-BEREICH) Nach Ausloggen oder Accountlöschung über "Zurück-Navigation" lässt die App abstürzen.

### ISSUE THREAD

**Issue by Rusi91** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#176]
Nachdem Ausloggen oder Löschung des Accounts -> Zurück-Navigation -> Absturz

![fehler_nach_Ausloggen_zurück](https://user-images.githubusercontent.com/41992838/157695933-fa564416-ac6b-4583-8128-7cadf9e9b68d.png)

Hierbei sollte die "Zurück-Navigation" im Login allgemein disabled werden.

**Comment by vairasza** [comment]
https://developer.android.com/guide/navigation/navigation-custom-back

wenn man von entercoursefragment einen kurs betritt, dann sollten wir den zurückbutton auf ein anderes fragment legen, weil ich denke nicht, dass der user will, dass er dadurch ausgeloggt wird oder so.

**Comment by Rusi91** [comment]
Zurück führt in dem Login jetzt zunichts.

![bugfix_back_button_login](https://user-images.githubusercontent.com/41992838/157702181-5bd15852-5ce3-4cd0-a36f-b56d558beff2.png)
