### ISSUE TITLE
(LOGIN) Email mit Leerzeichen löst Fehler aus.

### ISSUE THREAD

**Issue by Rusi91** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#217]
- [x] Email- und Passwortinput trimmen

**Comment by Rusi91** [comment]
Email und Passwort Input beim Login wird nun vorher getrimmt, bevor es weitergeleitet wird. [Zeile 82 und 83]
Email, Passwort und Nutzername Input beim Registrieren wird nun vorher getrimmt, bevor es weitergeleitet wird. [Zeile 77 - 79]

**Comment by julian1198** [comment]
Bug: #239
