### ISSUE TITLE
E/CourseMeetingViewModel: Databinding Error

### ISSUE THREAD

**Issue by Rusi91** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#231]
Beim reingehen in ein Meeting erscheint im run folgende Fehlermeldung:

![Fehler1](https://user-images.githubusercontent.com/41992838/160242663-264764a6-ca92-4dc5-bc72-e2d3b7541af7.png)

App läuft ohne ersichtliche Probleme weiter.

**Comment by vairasza** [comment]
sollte nicht mehr auftreten, da jeder tab nun ein eigenes viewmodel hat. ggf viewmodels der tabs mal im auge behalten.
