### ISSUE TITLE
Login Textfield

### ISSUE THREAD

**Issue by Kroellinger** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#28]
Das Login Textfield wird immer größer wenn man den Enter Button wiederholt drückt.
![grafik](https://user-images.githubusercontent.com/40796191/148206941-0f6b121f-3ce9-430e-8399-92a9ca509fe8.png)

**Comment by vairasza** [comment]
![Screenshot 2022-01-05 at 12 21 07](https://user-images.githubusercontent.com/46536619/148209689-f09b8f6e-ed91-4c7d-8b76-9453933fae3d.png)

TODO:

- Passwort muss mit Sternchen ersetzt werden - dafür sollte es in dem xml fragment ne property geben.
- mit dem Enter Button sollte "Einloggen" aktiviert werden.
- der Einloggen Button sollte über das Textfeld geschoben werden, wenn dieses offen ist.

**Comment by myPhilie** [comment]
> Das Login Textfield wird immer größer wenn man den Enter Button wiederholt drückt. ![grafik](https://user-images.githubusercontent.com/40796191/148206941-0f6b121f-3ce9-430e-8399-92a9ca509fe8.png)

wurde behoben, indem für Edittexts singleLine festgelegt wurde

**Comment by myPhilie** [comment]
> TODO:
> 
> * Passwort muss mit Sternchen ersetzt werden - dafür sollte es in dem xml fragment ne property geben.
> * der Einloggen Button sollte über das Textfeld geschoben werden, wenn dieses offen ist.

- Passwörter können nun getogglet werden
- Sichtbarkeit der Buttons wenn Textfeld offen ist wurde zum Teil behoben, funktioniert jedoch nicht vollständig (User kann Inhalt nun scrollen, Buttons werden aber je nach Displaygröße teilweise nicht oder unvollständig angezeigt

**Comment by myPhilie** [comment]
> * mit dem Enter Button sollte "Einloggen" aktiviert werden.

Ist das notwendig? Nutzer könnte nach Eingabe nochmals Blick auf eingegebene Daten werfen wollen

**Comment by vairasza** [comment]
> > * mit dem Enter Button sollte "Einloggen" aktiviert werden.
> 
> 
> 
> Ist das notwendig? Nutzer könnte nach Eingabe nochmals Blick auf eingegebene Daten werfen wollen

also ist jz kein muss, aber als option wird das glaub ich "erwartet".

**Comment by vairasza** [comment]
erdledigt
