### ISSUE TITLE
Course Code visibility

### ISSUE THREAD

**Issue by Rusi91** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#31]
Bei Erstellen des Kurses sollte die Nummer nicht angezeigt werden bevor sie erstellt wurde.

**Comment by vairasza** [comment]
![Screenshot 2022-01-05 at 16 24 16](https://user-images.githubusercontent.com/46536619/148243017-de7b18ce-4463-4dd6-afec-870135ea4215.png)

**Comment by myPhilie** [comment]
Button und Textfeld wurden entfernt. Beitrittsnummer soll jetzt im Chat unterhalb des Kurstitels angezeigt werden
