### ISSUE TITLE
Checkstyles ausbessern

### ISSUE THREAD

**Issue by vairasza** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#35]
- Ruslan
> - LoginFragment
> - RegistrationFragment 
> - MainActivity

- Micha
> - AuthAppRepository
> - LoginRegisterViewModel
> - EnterCourseFragment
> - CurrentCourseFragment

- Laurin
> - DBCourseCreation
> - CreateCourseViewModel 
> - CreateCourseFragment

- Philipp
> - EnterOrCreateCourseFragment
> - CourseModel 
> - LoggedInViewModel

**Comment by vairasza** [comment]
pull from "chat" branch
push into "chat" branch

**Comment by Rusi91** [comment]
LoginFragment, MainActivity und RegistrationFragment wurden bezüglich CheckStyle ausgebessert.

![checkstyle](https://user-images.githubusercontent.com/41992838/149180747-4ee651d4-b8b8-405a-a3ff-2f166c0cde97.png)
Zeile 107 wurde vorher als zu lang angegeben. der Inhalt aus "navController.navigate(..)" wurde in die Variable "toRegistrationFragment" umgelagert.

**Comment by vairasza** [comment]
> ...
> Betrifft "LoginFragment": ![checkstyle](https://user-images.githubusercontent.com/41992838/149180747-4ee651d4-b8b8-405a-a3ff-2f166c0cde97.png) Zeile 107 wurde vorher als zu lang angegeben. der Inhalt aus "navController.navigate(..)" wurde in die Variable "toRegistrationFragment" umgelagert.

Das Keyword ```var``` gibts in Java nicht. ```var``` => ```int```

Hab mein Zeugs auch fertig.
- Hab ein paar instance variables zu finals geändert
- Hab bei den instance variablen ```this``` hinzugefügt, damit sie besser erkannt werden
- bei den meisten Sachen hab ich keine sinnvolle JavaDoc gesehen und habs deswegen erstmal nur nen Platzhalter gesetzt
- meiste war eigentlich intendation, fehlende private modifier und verwurstelte imports

**Comment by Rusi91** [comment]
Danke. Hab in der falschen Programmiersprache gedacht. Bessere ich aus.
