### ISSUE TITLE
Beitrittsnummer teilen

### ISSUE THREAD

**Issue by myPhilie** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#38]
Möglichkeit hinzufügen, um die Beitrittsnummer zu teilen (Sharing oder Kopieren-Button, o.ä.)

**Comment by myPhilie** [comment]
Vorerst als Kopieren-Button in der Liste der beigetretenen Kurse

**Comment by vairasza** [comment]
erledigt
