### ISSUE TITLE
History

### ISSUE THREAD

**Issue by myPhilie** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#39]
Die App sollte ein "Ende" haben. Das heißt, wir brauchen eine Art Übersicht über bereits beigetretene Kurse, über die man dann auch in den Chat gelangt um beispielsweise alte Nachrichten nochmals durchzulesen.

**Comment by myPhilie** [comment]
UI wurde hinzugefügt.

TODO:

- bereits beigetretene Kurse in Liste laden
- Kopieren der Beitrittsnummer beim Drücken auf Kopieren-Icon in Kursitem
- Wechseln in den entsprechenden Kursraum beim Drücken auf Kurs

**Comment by vairasza** [comment]
erledigt
