### ISSUE TITLE
Hinweis für leere Kursliste/Chat

### ISSUE THREAD

**Issue by myPhilie** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#45]
- Wenn noch keinen Kursen beigetreten wurde sollte dafür ein Hinweis in der RecyclerView stehen
- Wenn in einem Kurs noch keine Nachrichten erstellt wurden, sollte ein Hinweis in der RecyclerView stehen

![image](https://user-images.githubusercontent.com/41925280/149661924-3a90ebf2-7d95-4207-b294-371d2158255e.png)

**Comment by vairasza** [comment]
erledigt
