### ISSUE TITLE
(LOGIN) Loginprozess

### ISSUE THREAD

**Issue by myPhilie** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#57]
- [x] Als Student:in möchte ich beim Login meine registrierte Email und Passwort eingeben um mich in die App einloggen zu können.

**Comment by Rusi91** [comment]
Nutzer*in loggt sich mit Email und Passwort ein. 
Fehlermeldungen (ausgelagertes Issue #58)

(Design noch nicht final; Anmeldung über Google, Facebook, etc. noch in Diskussion)

![logi1](https://user-images.githubusercontent.com/41992838/158212357-ef110872-b063-4bc0-b341-3ceadbcee77a.png)

Falls Email noch nicht verifiziert, erfolgt ein Hinweis mit der Möglichkeit der Neuversendung der Emailverifikation.

![logi2](https://user-images.githubusercontent.com/41992838/158212519-defa3390-ea52-41d1-82f4-9058b677ab59.png)
