### ISSUE TITLE
(KURSÜBERSICHT) Kursinformationen

### ISSUE THREAD

**Issue by Rusi91** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#76]
- [x] Als Student:in möchte ich Informationen über den Kurs wie den Dozenten bekommen, 
damit ich weiß wer meine Ansprechperson ist.

**Comment by julian1198** [comment]
Der Dozent, Institut und Name wird bereits angezeigt. Es fehlt noch eine Teilnehmerliste sowie das Ausklappen der Beschreibung.

**Comment by julian1198** [comment]
Die userliste ist jetzt in dem Commit a5312f7ef985f9a85e105839cf074d7f36ff294c (Branch: newDatastructur) hinzugefügt worden. Das Design ist aber noch nicht besonders ansprechend und die Bilder werden nicht richtig angezeitgt. @myPhilie und @vairasza könntet ihr da bitt einmal drüber schauen.
