### ISSUE TITLE
(CHAT) Nachrichten suchen

### ISSUE THREAD

**Issue by vairasza** [ASE-Projekte-WS-2021/ase-ws-21-unser-horsaal#78]
- [ ] Als Student:in möchte ich die Möglichkeit haben, Fragen über ein Suchfeld zu suchen, damit ich diese schneller finde.

**Comment by myPhilie** [comment]
Es wurde ein Suchfeld eingebaut, über das man Fragen nach Inhalt, Hashtags und Tags suchen kann
